-- =========================================================
-- COMEDOR UCR - SUPABASE
-- Ejecuta TODO este archivo en Supabase > SQL Editor.
-- =========================================================

create extension if not exists pgcrypto;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

drop function if exists public.is_admin();
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  );
$$;

create table if not exists public.food_items (
  id uuid primary key default gen_random_uuid(),
  legacy_id text,
  category text not null check (category in (
    'desayuno_principal','desayuno_acompanamiento','desayuno_extra','desayuno_bebida',
    'almuerzo_principal','almuerzo_acompanamiento','almuerzo_ensalada','almuerzo_bebida'
  )),
  name text not null,
  created_at timestamptz not null default now(),
  unique(category, name)
);

create table if not exists public.weekly_menu (
  id bigint generated by default as identity primary key,
  day text not null check (day in ('lunes','martes','miercoles','jueves','viernes')),
  meal text not null check (meal in ('desayuno','almuerzo')),
  category text not null check (category in ('principal','acompanamiento','extra','ensalada','bebida')),
  item_id uuid not null references public.food_items(id) on delete cascade,
  unique(day, meal, category, item_id)
);

create index if not exists idx_food_items_category on public.food_items(category);
create index if not exists idx_weekly_menu_day on public.weekly_menu(day);
create index if not exists idx_weekly_menu_item on public.weekly_menu(item_id);

alter table public.admin_users enable row level security;
alter table public.food_items enable row level security;
alter table public.weekly_menu enable row level security;

-- El menú es público de lectura.
drop policy if exists "public can read food items" on public.food_items;
create policy "public can read food items"
on public.food_items for select
using (true);

drop policy if exists "admins can insert food items" on public.food_items;
create policy "admins can insert food items"
on public.food_items for insert to authenticated
with check (public.is_admin());

drop policy if exists "admins can update food items" on public.food_items;
create policy "admins can update food items"
on public.food_items for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admins can delete food items" on public.food_items;
create policy "admins can delete food items"
on public.food_items for delete to authenticated
using (public.is_admin());

-- El menú semanal también es público de lectura.
drop policy if exists "public can read weekly menu" on public.weekly_menu;
create policy "public can read weekly menu"
on public.weekly_menu for select
using (true);

drop policy if exists "admins can insert weekly menu" on public.weekly_menu;
create policy "admins can insert weekly menu"
on public.weekly_menu for insert to authenticated
with check (public.is_admin());

drop policy if exists "admins can update weekly menu" on public.weekly_menu;
create policy "admins can update weekly menu"
on public.weekly_menu for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admins can delete weekly menu" on public.weekly_menu;
create policy "admins can delete weekly menu"
on public.weekly_menu for delete to authenticated
using (public.is_admin());

-- Permite que el usuario administrador vea su propia fila si fuese necesario.
drop policy if exists "admins can read own admin row" on public.admin_users;
create policy "admins can read own admin row"
on public.admin_users for select to authenticated
using (user_id = auth.uid());

-- =========================================================
-- DATOS INICIALES
-- =========================================================
insert into public.food_items (legacy_id, category, name) values
('d-p1','desayuno_principal','Gallo pinto'),
('d-p2','desayuno_principal','Huevos revueltos'),
('d-p3','desayuno_principal','Pan con pollo'),
('d-p4','desayuno_principal','Sándwich de queso'),
('d-a1','desayuno_acompanamiento','Huevo frito'),
('d-a2','desayuno_acompanamiento','Natilla'),
('d-a3','desayuno_acompanamiento','Tortilla y queso'),
('d-a4','desayuno_acompanamiento','Fruta picada'),
('d-e1','desayuno_extra','Pan casero'),
('d-e2','desayuno_extra','Plátano maduro'),
('d-e3','desayuno_extra','Avena'),
('d-e4','desayuno_extra','Fruta de temporada'),
('d-b1','desayuno_bebida','Café'),
('d-b2','desayuno_bebida','Té'),
('d-b3','desayuno_bebida','Refresco natural'),
('a-p1','almuerzo_principal','Pollo en salsa'),
('a-p2','almuerzo_principal','Carne en salsa'),
('a-p3','almuerzo_principal','Filete de pescado'),
('a-p4','almuerzo_principal','Arroz con pollo'),
('a-p5','almuerzo_principal','Spaghetti a la boloñesa'),
('a-p6','almuerzo_principal','Picadillo de papa'),
('a-a1','almuerzo_acompanamiento','Arroz blanco'),
('a-a2','almuerzo_acompanamiento','Frijoles molidos'),
('a-a3','almuerzo_acompanamiento','Puré de papa'),
('a-a4','almuerzo_acompanamiento','Pan de ajo'),
('a-e1','almuerzo_ensalada','Ensalada fresca'),
('a-e2','almuerzo_ensalada','Repollo y tomate'),
('a-e3','almuerzo_ensalada','Ensalada mixta'),
('a-e4','almuerzo_ensalada','Ensalada César'),
('a-b1','almuerzo_bebida','Refresco natural'),
('a-b2','almuerzo_bebida','Fresco de cas'),
('a-b3','almuerzo_bebida','Fresco de sandía'),
('a-b4','almuerzo_bebida','Fresco de tamarindo')
on conflict (category, name) do nothing;

insert into public.weekly_menu (day, meal, category, item_id)
select v.day, v.meal, v.category, f.id
from (values
('lunes','desayuno','principal','d-p1'),('lunes','desayuno','acompanamiento','d-a2'),('lunes','desayuno','extra','d-e1'),('lunes','desayuno','bebida','d-b1'),('lunes','desayuno','bebida','d-b2'),('lunes','desayuno','bebida','d-b3'),
('lunes','almuerzo','principal','a-p4'),('lunes','almuerzo','acompanamiento','a-a2'),('lunes','almuerzo','ensalada','a-e1'),('lunes','almuerzo','bebida','a-b1'),
('martes','desayuno','principal','d-p2'),('martes','desayuno','acompanamiento','d-a3'),('martes','desayuno','extra','d-e4'),('martes','desayuno','bebida','d-b1'),('martes','desayuno','bebida','d-b2'),('martes','desayuno','bebida','d-b3'),
('martes','almuerzo','principal','a-p1'),('martes','almuerzo','principal','a-p2'),('martes','almuerzo','acompanamiento','a-a1'),('martes','almuerzo','acompanamiento','a-a2'),('martes','almuerzo','ensalada','a-e2'),('martes','almuerzo','bebida','a-b2'),
('miercoles','desayuno','principal','d-p3'),('miercoles','desayuno','acompanamiento','d-a2'),('miercoles','desayuno','extra','d-e4'),('miercoles','desayuno','bebida','d-b1'),('miercoles','desayuno','bebida','d-b2'),('miercoles','desayuno','bebida','d-b3'),
('miercoles','almuerzo','principal','a-p3'),('miercoles','almuerzo','acompanamiento','a-a3'),('miercoles','almuerzo','ensalada','a-e3'),('miercoles','almuerzo','bebida','a-b3'),
('jueves','desayuno','principal','d-p1'),('jueves','desayuno','acompanamiento','d-a1'),('jueves','desayuno','extra','d-e2'),('jueves','desayuno','bebida','d-b1'),('jueves','desayuno','bebida','d-b2'),('jueves','desayuno','bebida','d-b3'),
('jueves','almuerzo','principal','a-p1'),('jueves','almuerzo','principal','a-p2'),('jueves','almuerzo','acompanamiento','a-a1'),('jueves','almuerzo','acompanamiento','a-a2'),('jueves','almuerzo','ensalada','a-e1'),('jueves','almuerzo','bebida','a-b1'),
('viernes','desayuno','principal','d-p4'),('viernes','desayuno','acompanamiento','d-a4'),('viernes','desayuno','extra','d-e3'),('viernes','desayuno','bebida','d-b1'),('viernes','desayuno','bebida','d-b2'),('viernes','desayuno','bebida','d-b3'),
('viernes','almuerzo','principal','a-p5'),('viernes','almuerzo','acompanamiento','a-a4'),('viernes','almuerzo','ensalada','a-e4'),('viernes','almuerzo','bebida','a-b4')
) as v(day,meal,category,legacy_id)
join public.food_items f on f.legacy_id = v.legacy_id
on conflict (day, meal, category, item_id) do nothing;

-- Después de crear el usuario en Authentication, ejecuta:
-- insert into public.admin_users(user_id)
-- select id from auth.users where email = 'TU_CORREO_ADMIN';
